Week 5, Assignment C1:

Logistic Regression with Yahoo! Finance API in Python

In this notebook, we will study Logistic Regression using the Yahoo! Finance API in Python.

Please complete the lines bellow where you see "#TODO".

In [1]:
#Objective 1.
#Use this cell to import the Numpy (as np), Pandas (as pd), and YFinance (as yf) packages.

import numpy as np
import  pandas as pd
import yfinance as yf

from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.model_selection import cross_val_score
from pandas_datareader import data as pdr
yf.pdr_override()

In [2]:
#Objective 2.
#Select a stock symbol for a stock whose historical data is available on the Yahoo! Finance website.  Store the
#string of your chosen symbol to the new variable "stock_symbol".

stock_symbol = 'AAPL'

In [3]:
#Objective 3.
#Use the function "pdr.get_data_yahoo(stock_symbol, start_date, end_date)" to generate a Pandas dataframe of
#historical stock data for your chosen stock.  Retain only the first four columns of the dataframe.  Be sure to 
#drop any rows containing NaN's, and take a peek at the resulting dataframe to make sure everything looks good.
df = pdr.get_data_yahoo('AAPL', '2020-10-31', '2021-10-31')
df = df.iloc[:, :4]
df = df.dropna()
df.head()


[*********************100%***********************]  1 of 1 completed


Open        High         Low       Close
Date                                                      
2020-10-30  111.059998  111.989998  107.720001  108.860001
2020-11-02  109.110001  110.680000  107.320000  108.769997
2020-11-03  109.660004  111.489998  108.730003  110.440002
2020-11-04  114.139999  115.589996  112.349998  114.949997
2020-11-05  117.949997  119.620003  116.870003  119.029999

In [4]:
#Objective 4.
#Use the historical data to define some predictor variables.  Add these variables to the dataframe.  Include, at a
#minimum, (Predictor.I) the rolling average closing price over the past fifteen (15) days and (Predictor.II) the
#change in opening price over the past one (1) day.  Be sure to again drop any rows containing NaN's, and take a
#peek at the resulting dataframe to make sure everything looks good.  Store the dataframe as the new variable "X".

df['Close_15_Rolling'] = df['Close'].rolling(window = 15).mean()
df['Open_1_Change'] = df['Open'] - df['Open'].shift(1)
df = df.dropna()
X = df
X

Open        High         Low       Close  Close_15_Rolling  \
Date                                                                           
2020-11-19  117.589996  119.059998  116.809998  118.639999        116.490000   
2020-11-20  118.639999  118.769997  117.290001  117.339996        117.055333   
2020-11-23  117.180000  117.620003  113.750000  113.849998        117.394000   
2020-11-24  113.910004  115.849998  112.589996  115.169998        117.709333   
2020-11-25  115.550003  116.750000  115.169998  116.029999        117.781333   
2020-11-27  116.570000  117.489998  116.220001  116.589996        117.618666   
2020-11-30  116.970001  120.970001  116.809998  119.050003        117.642666   
2020-12-01  121.010002  123.470001  120.010002  122.720001        118.069333   
2020-12-02  122.019997  123.370003  120.889999  123.080002        118.543333   
2020-12-03  123.519997  123.779999  122.209999  122.940002        118.773333   
2020-12-04  122.599998  122.860001  121.519997  122.250000        118.976000   
2020-12-07  122.309998  124.570000  122.250000  123.750000        119.275333   
2020-12-08  124.370003  124.980003  123.089996  124.379997        119.547333   
2020-12-09  124.529999  125.949997  121.000000  121.779999        119.706666   
2020-12-10  120.500000  123.870003  120.150002  123.239998        120.053999   
2020-12-11  122.430000  122.760002  120.550003  122.410004        120.305333   
2020-12-14  122.599998  123.349998  121.540001  121.779999        120.601333   
2020-12-15  124.339996  127.900002  124.129997  127.879997        121.536666   
2020-12-16  127.410004  128.369995  126.559998  127.809998        122.379333   
2020-12-17  128.899994  129.580002  128.039993  128.699997        123.224000   
2020-12-18  128.960007  129.100006  126.120003  126.660004        123.895333   
2020-12-21  125.019997  128.309998  123.449997  128.229996        124.507333   
2020-12-22  131.610001  134.410004  129.649994  131.880005        125.118000   
2020-12-23  132.160004  132.429993  130.779999  130.960007        125.643333   
2020-12-24  131.320007  133.460007  131.100006  131.970001        126.245333   
2020-12-28  133.990005  137.339996  133.509995  136.690002        127.208000   
2020-12-29  138.050003  138.789993  134.339996  134.869995        127.949333   
2020-12-30  135.580002  135.990005  133.399994  133.720001        128.572000   
2020-12-31  134.080002  134.740005  131.720001  132.690002        129.299334   
2021-01-04  133.520004  133.610001  126.760002  129.410004        129.710667   
...                ...         ...         ...         ...               ...   
2021-09-20  143.800003  144.839996  141.270004  142.940002        150.982666   
2021-09-21  143.929993  144.600006  142.779999  143.429993        150.336666   
2021-09-22  144.449997  146.429993  143.699997  145.850006        149.937999   
2021-09-23  146.649994  147.080002  145.639999  146.830002        149.559333   
2021-09-24  145.660004  147.470001  145.559998  146.919998        149.110667   
2021-09-27  145.470001  145.960007  143.820007  145.369995        148.515333   
2021-09-28  143.250000  144.750000  141.690002  141.910004        147.530000   
2021-09-29  142.470001  144.449997  142.029999  142.830002        146.711333   
2021-09-30  143.660004  144.380005  141.279999  141.500000        145.873333   
2021-10-01  141.899994  142.919998  139.110001  142.649994        145.451999   
2021-10-04  141.759995  142.210007  138.270004  139.139999        144.757999   
2021-10-05  139.490005  142.240005  139.360001  141.110001        144.290666   
2021-10-06  139.470001  142.149994  138.369995  142.000000        143.821999   
2021-10-07  143.059998  144.220001  142.720001  143.289993        143.455332   
2021-10-08  144.029999  144.179993  142.559998  142.899994        143.244666   
2021-10-11  142.270004  144.809998  141.809998  142.809998        143.235999   
2021-10-12  143.229996  143.250000  141.039993  141.509995        143.107999   
2021-10-13  141.24

In [5]:
#Objective 5.
#Define the target or dependent variable to be one (1) if the change in closing price over the past one (1) day is
#nonnegative and negative one (-1) if the change in closing price over the past one (1) day is negative.  This
#variable's values should be forward-looking (i.e., you should subtract today's price from tomorrow's price rather
#than subtracting yesterday's price from today's price).  Store the resulting values as the new variable "y".  You
#may find the "np.where(*args)" function to be useful.  Look it up in Numpy documentation for support.

y = np.where(df['Close'].shift(-1) - df['Close'] >= 0, 1, -1)
y

array([-1, -1,  1,  1,  1,  1,  1,  1, -1, -1,  1,  1, -1,  1, -1, -1,  1,
       -1,  1, -1,  1,  1, -1,  1,  1, -1, -1, -1, -1,  1, -1,  1,  1, -1,
       -1,  1, -1, -1,  1,  1,  1,  1,  1,  1, -1, -1, -1,  1,  1, -1,  1,
       -1,  1, -1, -1, -1,  1, -1, -1, -1,  1, -1, -1, -1, -1,  1,  1, -1,
       -1, -1,  1, -1,  1, -1,  1, -1,  1,  1, -1, -1, -1,  1, -1, -1,  1,
        1,  1, -1,  1,  1,  1,  1,  1,  1,  1, -1,  1, -1,  1, -1,  1, -1,
        1, -1,  1,  1, -1, -1, -1, -1,  1, -1,  1,  1,  1, -1, -1, -1,  1,
        1, -1, -1, -1,  1, -1,  1, -1, -1, -1, -1, -1,  1, -1,  1,  1,  1,
        1, -1,  1,  1, -1,  1,  1, -1,  1,  1, -1, -1, -1,  1,  1,  1,  1,
        1,  1,  1, -1,  1, -1,  1,  1, -1, -1, -1,  1, -1,  1,  1,  1, -1,
       -1,  1,  1, -1,  1, -1,  1, -1, -1, -1,  1,  1,  1,  1, -1, -1,  1,
        1,  1, -1, -1, -1,  1,  1, -1,  1,  1,  1,  1, -1, -1, -1,  1, -1,
        1, -1, -1, -1,  1,  1,  1,  1, -1, -1,  1, -1,  1, -1,  1,  1,  1,
       -1, -1, -1, -1,  1

In [7]:
#Objective 6.
#Split the data into training and test sets, putting the first seventy percent (70%) of the data in the training
#set.

index = int(0.7*len(X))
X_train, X_test, y_train, y_test = X[:index], X[index:], y[:index], y[index:]

In [9]:
#Objective 7.
#Instantiate the Logistic Regression model object, and use its ".fit(*args)" method to fit the model to the 
#training data.

logistic = LogisticRegression()
logistic = logistic.fit(X_train, y_train)

C:\Users\user\Anaconda2\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [10]:
#Objective 8.
#Examine the model's coefficients by using its ".coef_" method.

pd.DataFrame(zip(X.columns, np.transpose(logistic.coef_)))

0                        1
0              Open   [-0.10645558981901075]
1              High    [0.28860936968728523]
2               Low    [0.03469701990018049]
3             Close   [-0.22490082657083008]
4  Close_15_Rolling  [0.0018196044950136037]
5     Open_1_Change  [-0.028673383848419318]

In [11]:
#Objective 9.
#Use the model's ".predict_proba(*args)" and ".predict(*args)" methods to generate predictions over the test set.

probabilities = logistic.predict_proba(X_test)
predictions = logistic.predict(X_test)
print(probabilities)
print(predictions)

[[0.57168415 0.42831585]
 [0.49002224 0.50997776]
 [0.5918813  0.4081187 ]
 [0.54266362 0.45733638]
 [0.50474046 0.49525954]
 [0.44040602 0.55959398]
 [0.51660149 0.48339851]
 [0.53921205 0.46078795]
 [0.53457827 0.46542173]
 [0.52719654 0.47280346]
 [0.5656182  0.4343818 ]
 [0.54915085 0.45084915]
 [0.53568119 0.46431881]
 [0.56247712 0.43752288]
 [0.47351407 0.52648593]
 [0.5425312  0.4574688 ]
 [0.54949162 0.45050838]
 [0.60361596 0.39638404]
 [0.57301507 0.42698493]
 [0.52322542 0.47677458]
 [0.378467   0.621533  ]
 [0.44776826 0.55223174]
 [0.59004429 0.40995571]
 [0.55667656 0.44332344]
 [0.52477528 0.47522472]
 [0.5085702  0.4914298 ]
 [0.49964831 0.50035169]
 [0.57233141 0.42766859]
 [0.52688361 0.47311639]
 [0.59240204 0.40759796]
 [0.44483971 0.55516029]
 [0.56042336 0.43957664]
 [0.58559523 0.41440477]
 [0.56097942 0.43902058]
 [0.5507821  0.4492179 ]
 [0.49486814 0.50513186]
 [0.30421515 0.69578485]
 [0.47415509 0.52584491]
 [0.45696442 0.54303558]
 [0.57137925 0.42862075]


In [12]:
#Objective 10.
#Use the function "metrics.confusion_matrix(*args)" to create a confusion matrix comparing the predicted and true
#classification labels over the test set.

print(metrics.confusion_matrix(y_test, predictions))

[[28  5]
 [25 14]]


In [13]:
#Objective 11.
#Calculate the model's accuracy on the test set using its ".score(*args)" method.

print(logistic.score(X_test, y_test))

0.5833333333333334


In [14]:
#Objective 12.
#Use five-fold cross validation to cross-check the accuracy of the model over different held-out test sets.  This
#is where you should use the function "cross_val_score(*args)".

cross_val = cross_val_score(LogisticRegression(), X, y, scoring='accuracy' , cv=5)
print(cross_val)
print(cross_val.mean())

[0.52083333 0.4375     0.52083333 0.58333333 0.47826087]
0.5081521739130435


C:\Users\user\Anaconda2\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda2\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda2\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda2\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda2\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w